import importlib
import traceback

plugins = [
    "SNC.modules.basic.administrator",
    "SNC.modules.basic.adminlist",
    "SNC.modules.basic.afk",
    "SNC.modules.basic.animation",
    "SNC.modules.basic.autoscroll",
    "SNC.modules.basic.banall",
    "SNC.modules.basic.broadcast",
    "SNC.modules.basic.carbon",
    "SNC.modules.basic.clone",
    "SNC.modules.basic.create",
    "SNC.modules.basic.define",
    "SNC.modules.basic.eval_exec",
    "SNC.modules.basic.git_commands",
    "SNC.modules.basic.google",
    "SNC.modules.basic.invite",
    "SNC.modules.basic.joinleave",
    "SNC.modules.basic.locks",
    "SNC.modules.basic.lyrics",
    "SNC.modules.basic.mention",
    "SNC.modules.basic.metrics",
    "SNC.modules.basic.misc",
    "SNC.modules.basic.music",
    "SNC.modules.basic.nekobin",
    "SNC.modules.basic.pats",
    "SNC.modules.basic.ping",
    "SNC.modules.basic.profile",
    "SNC.modules.basic.purge",
    "SNC.modules.basic.quote",
    "SNC.modules.basic.sangmata",
    "SNC.modules.basic.screenshot",
    "SNC.modules.basic.stats",
    "SNC.modules.basic.stickers",
    "SNC.modules.basic.tagalert",
    "SNC.modules.basic.tagall",
    "SNC.modules.basic.telegraph",
    "SNC.modules.basic.translate",
    "SNC.modules.basic.ud",
    "SNC.modules.basic.upload_files",
    "SNC.modules.basic.vctools",
    "SNC.modules.basic.vulgar",
    "SNC.modules.basic.weather",
    "SNC.modules.basic.whois",
    "SNC.modules.fun.autopic",
    "SNC.modules.fun.emoji",
    "SNC.modules.fun.stickers",
    "SNC.modules.fun.text_api",
    "SNC.modules.fun.texts",
    "SNC.modules.globals.global",
    "SNC.modules.private.apmguarde",
    "SNC.modules.private.pmguard",
    "SNC.modules.spam.Spam",
    "SNC.modules.spam.areplyraid",
    "SNC.modules.spam.dmspam",
    "SNC.modules.spam.replyraid",
    "SNC.modules.spam.watcher",
    "SNC.modules.sudo.sudos",
    "SNC.modules.updater.update",
    "SNC.modules.help.help",
]

for plugin in plugins:
    try:
        importlib.import_module(plugin)
        print(f"✅ Loaded: {plugin}")
    except Exception as e:
        print(f"⚠️ Skip: {plugin} — {e}")
